version: 2.1

workflows:
  flow:
    jobs:
      - test
      - kaniko-publish/publish:
          requires:
            - test
          # filters:
          #   branches:
          #     only:
          #       - master

orbs:
  kaniko-publish:
    description: |
      Build and publish container images to container registries *without* docker

      Under the hood this uses Google's Kaniko project, but aims to provide the
      same interface as the circleci/docker-publish orb

    executors:
      kaniko-debug:
        docker:
          - image: glenathan/circleci-kaniko:build-3
        working_directory: /workspace

    commands:
      check:
        description: |
          Sanity check to make sure you can push a container image.

            * check that $DOCKER_LOGIN and $DOCKER_PASSWORD environment variables are set
            * run docker login to ensure that you can push the built image
        steps:
          - run:
              name: kaniko-publish: Check Environment Variables
              command: |
                if [[ -z "${DOCKER_LOGIN}" ]]; then
                  echo "DOCKER_LOGIN is not set, will not be able to push image."
                  exit 1
                fi

                if [[ -z "${DOCKER_PASSWORD}" ]]; then
                  echo "DOCKER_PASSWORD is not set, will not be able to push image."
                  exit 1
                fi
          - run:
              name: kaniko-publish: Simulate Docker Login
              command: |
                auth=$(printf "${DOCKER_LOGIN}:${DOCKER_PASSWORD}" | base64)
                mkdir -p /kaniko/.docker
                cat \<< JSON > /kaniko/.docker/config.json
                {
                  "auths": {
                    "https://index.docker.io/v1/": {
                      "auth": "${auth}"
                    }
                  }
                }
                JSON

      build_and_push:
        description: Builds, tags and pushes a container image
        steps:
          - run:
              name: kaniko-publish: build and push container
              command: /kaniko/executor --destination ${DOCKER_LOGIN}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}

    jobs:
      publish:
        executor: kaniko-debug
        steps:
          - checkout
          - check
          - build_and_push

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - run: pwd

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run lint

      - run:
          command: npm test
          when: always
